"
Abstract superclass grouping common behavior for Machine Learning visualizations. Methods implemented in this class should be related with plotting machine learning models results.

Public API and Key Messages

- message one   
- message two 
- (for bonus points) how to create instances.

   One simple example is simply gorgeous.
 
Internal Representation and Key Implementation Points.


    Implementation Points
"
Class {
	#name : #AIViz,
	#superclass : #Object,
	#category : #'AI-Viz'
}
